# Generated by Django 4.1.6 on 2023-02-07 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_disc_owner_alter_disc_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disc',
            name='owner',
        ),
        migrations.AlterField(
            model_name='disc',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.artist'),
        ),
    ]
