# Generated by Django 4.1.6 on 2023-02-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
